set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

set-window-option -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'


bind-key -r f run-shell "tmux neww ~/.tmux_sessionizer"
bind-key -r i run-shell "tmux neww ~/.tmux_cht.sh"
# run fzf
bind-key -n C-1 select-pane -t 1
bind-key -n C-2 select-pane -t 2
bind-key -n C-3 select-pane -t 3
bind-key -n C-4 select-pane -t 4
bind-key -n C-5 select-pane -t 5


set -g mouse on
set -g history-limit 80000
